// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATimePicker: typeof import('ant-design-vue/es')['TimePicker']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ButtonsItem: typeof import('./components/Form/ButtonsItem')['default']
    CheckboxGroupItem: typeof import('./components/Form/CheckboxGroupItem')['default']
    CheckboxItem: typeof import('./components/Form/CheckboxItem')['default']
    ColorPicker: typeof import('./components/ColorPicker.vue')['default']
    FormItem: typeof import('./components/Form/FormItem')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputItem: typeof import('./components/Form/InputItem')['default']
    LangSelect: typeof import('./components/LangSelect.vue')['default']
    LangSelectTsx: typeof import('./components/LangSelectTsx')['default']
    RadioGroupItem: typeof import('./components/Form/RadioGroupItem')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectItem: typeof import('./components/Form/SelectItem')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    SwitchItem: typeof import('./components/Form/SwitchItem')['default']
    UploadItem: typeof import('./components/Form/UploadItem')['default']
  }
}
