// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATimePicker: typeof import('ant-design-vue/es')['TimePicker']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ButtonsItem: typeof import('./components/Form/ButtonsItem')['default']
    CheckboxGroupItem: typeof import('./components/Form/CheckboxGroupItem')['default']
    CheckboxItem: typeof import('./components/Form/CheckboxItem')['default']
    ColorPicker: typeof import('./components/ColorPicker.vue')['default']
    FormItem: typeof import('./components/Form/FormItem')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputItem: typeof import('./components/Form/InputItem')['default']
    LangSelect: typeof import('./components/LangSelect.vue')['default']
    LangSelectTsx: typeof import('./components/LangSelectTsx')['default']
    RadioGroupItem: typeof import('./components/Form/RadioGroupItem')['default']
    SelectItem: typeof import('./components/Form/SelectItem')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    SwitchItem: typeof import('./components/Form/SwitchItem')['default']
    UploadItem: typeof import('./components/Form/UploadItem')['default']
  }
}

export { }
